# Desenvolvimento
spring.datasource.url=jdbc:postgresql://localhost:5432/banco_sangue
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Logs
logging.level.root=INFO
logging.level.br.edu.ifrn.bancosangue=DEBUG