# Producao - valores virao de variaveis de ambiente
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/banco_sangue}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:12345}

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

# Logs
logging.level.root=WARN
logging.level.br.edu.ifrn.bancosangue=INFO

# Actuator (mais restrito em producao)
management.endpoints.web.exposure.include=health,info